all:
  children:
    pve:
      hosts:
        zeus:
          ansible_host: 192.168.20.10
    swarm:
      hosts:
        swarm01:
          ansible_host: 192.168.20.11
          ansible_user: serveradmin
        swarm02:
          ansible_host: 192.168.20.12
          ansible_user: serveradmin
        swarm03:
          ansible_host: 192.168.20.13
          ansible_user: serveradmin
    pis:
      hosts:
        micro01:
          ansible_host: 192.168.20.21