name: Caddy Image CI

on:
  push:
    branches: [ main ]
    paths:
      - deploy/reverse_proxy/caddy/**

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}-caddy

jobs:

  build-and-push-caddy-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read Caddy version
        id: caddy
        run: echo "version=$(grep ARG deploy/reverse_proxy/caddy/Dockerfile | cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: deploy/reverse_proxy/caddy/
          push: true
          tags: |
            type=raw,value=${{ steps.caddy.outputs.version }}
            type=raw,value=latest